# TODO create clear structure
# CAD
reads_file_path: "../Data/454/454.fasta"
haplotype_file_path: "./data/reference//REF.fasta"
# general
name: "HIV_CAD"
save: True
load: True
data: created
# illumina, 454, created or testing
alignment: ngs_alignment # de_novo_alignment or ngs_alignment
#data: created
number_of_spots: 3000
max_read_length: 1006 #9721 # length of HBX2
#haplotype_length: 9721 # length of HBX2
#haplotype_length: 9850 # length of HBX2 # adapted for positions in the back
haplotype_length: 1000 # length of HBX2
#max_read_length: 252
max_created_read_length: 250
n_clusters: 5
verbose: 1 # set to 1 if you want tensorflow and Kmeans to give feedback on their progress
max_cluster: 5

number_of_reads_per_file: 1
# create Data


# alignment
min_alignment_score: 60
min_read_length: 150
batch_size: 100

# path
hxb2_path: ./data/reference/hxb2.fasta
#ref_path: ./data/reference/REF
ref_path: ./data/reference/REF_aligned

#created:
#  reads_path: ./data/created/reads
#  one_hot_path: ./data/created/encoded_reads
#  hxb2_path: ./data/created/reference/hxb2.fasta
#  ref_path: ./data/created/reference/REF.fasta
#  cluster_path: ./results/created/clusters/
#  aligned_path: ./results/created/aligned/

454:
  reads_path: ./data/454
  mapped_reads_path: ./data/454_mapped
  #  one_hot_path: ./data/454_encoded_reads
  one_hot_path: ./data/454_encoded_snps
  #  one_hot_path: ./data/454/encoded/
  cluster_path: ./results/clusters/
  aligned_path: ./results/aligned/
  autoencoder_weights_path: ./results/models/autoencoder_weights
  output_path: ./results/454_output.fasta
  #  weights_path: ./results/models/454_weights
  weights_path: ./results/models/454_weights_snps
  ref_path: ./data/reference/REF
  aligned_ref_path: ./data/reference/aligned_REF
  unaligned_ref_path: ./data/reference/unaligned_454_REF
  number_of_batches: 100000
  batch_size: 10000
  #  haplotype_length: 5000
  #  haplotype_length: 4860
  haplotype_length: 9721
  #  haplotype_length: 2432
  #  centroids_name: centroids
  haplotype_start: 789
  haplotype_end: 1186
  centroids_name: centroids_snp
  pooling: True
  SNP_pos: ./data/454_SNP_pos
  n_clusters: 5
  snp_positions: ./data/reference/snp_positions.txt

per_gene_454:
  reads_path: ./data/454
  mapped_reads_path: ./data/454_mapped.sam

  #  p2p6
  haplotype_start: 1878
  haplotype_end: 2292
  one_hot_path: ./data/454_encoded_reads_p2p6
  weights_path: ./results/models/454_weights_p2p6
  centroids_name: centroids_p2p6
  n_clusters: 5

  # p24
  #  haplotype_start: 1185
  #  haplotype_end: 1879
  #  one_hot_path: ./data/454_encoded_reads_p24
  #  weights_path: ./results/models/454_weights_p24
  #  centroids_name: centroids_p24

  # p17
  #  haplotype_start: 789
  #  haplotype_end: 1186
  #  one_hot_path: ./data/454_encoded_reads_p17
  #  weights_path: ./results/models/454_weights_p17
  #  centroids_name: centroids_p17

  cluster_path: ./results/clusters/
  aligned_path: ./results/aligned/
  autoencoder_weights_path: ./results/models/autoencoder_weights
  output_path: ./results/454_output.fasta
  ref_path: ./data/reference/REF
  unaligned_ref_path: ./data/reference/unaligned_454_REF
  number_of_batches: 100000
  batch_size: 200
  haplotype_length: 9721
  pooling: True

illumina:
  reads_path: ./data/Illumina
  mapped_reads_path: ./data/illumina_mapped
  #  one_hot_path: ./data/illumina_encoded_reads
  one_hot_path: ./data/illumina_encoded_snps
  #  weights_path: ./results/models/illumina_weights
  weights_path: ./results/models/illumina_weights_snps
  output_path: ./results/illumina_output.fasta
  ref_path: ./data/reference/REF
  aligned_ref_path: ./data/reference/aligned_REF
  unaligned_ref_path: ./data/reference/unaligned_illumina_REF
  haplotype_length: 9721
  number_of_batches: 9721
  #  centroids_name: illumina_centroids
  centroids_name: illumina_centroids_snps
  batch_size: 500
  n_clusters: 5
  pooling: False
  snp_positions: ./data/reference/snp_positions.txt

created:
  reads_path: ./data/created/reads
  mapped_reads_path: ./data/created/mapped
  one_hot_path: ./data/created/encoded_reads
  weights_path: ./results/models/created_weights_dataset
  output_path: ./results/created_output_dataset.fasta
  #  ref_path: ./data/reference/created_REF
  ref_path: ./data/created/reference/REF
  aligned_ref_path: ./data/created/reference/aligned_REF
  og_path: ./data/created/reference/og_REF.fasta
  longest_path: ./data/created/reference/longest_REF
  snp_positions: ./data/created/reference/snp_positions
  haplotype_length: 4000
  number_of_batches: 1000
  batch_size: 100
  centroids_name: centroids_created
  coverage: 25
  error: todo
  pooling: False
  read_length: 500
  number_of_strains: 5
  n_clusters: 5





