# TODO create clear structure
# CAD
reads_file_path: "../Data/454/454.fasta"
haplotype_file_path: "./data/reference//REF.fasta"
# general
name: "HIV_CAD"
save: True
load: True
data: created
# illumina, 454 or created
#data: created
number_of_spots: 3000
max_read_length: 1006 #9721 # length of HBX2, 454
#haplotype_length: 9850 # length of HBX2 # adapted for positions in the back
haplotype_length: 1000 # length of HBX2
#max_read_length: 252
max_created_read_length: 250
n_clusters: 5
verbose: 1 # set to 1 if you want tensorflow and Kmeans to give feedback on their progress
max_cluster: 5

number_of_reads_per_file: 1
# create Data


# alignment
min_alignment_score: 60
min_read_length: 150
batch_size: 100

# path
hxb2_path: ./data/reference/hxb2.fasta
#ref_path: ./data/reference/REF
ref_path: ./data/reference/REF_aligned

#created:
#  reads_path: ./data/created/reads
#  one_hot_path: ./data/created/encoded_reads
#  hxb2_path: ./data/created/reference/hxb2.fasta
#  ref_path: ./data/created/reference/REF.fasta
#  cluster_path: ./results/created/clusters/
#  aligned_path: ./results/created/aligned/

454:
  reads_path: ./data/454
  mapped_reads_path: ./data/454_mapped
  #  one_hot_path: ./data/454_encoded_reads
  one_hot_path: ./data/454_encoded_snps
  #  one_hot_path: ./data/454/encoded/
  cluster_path: ./results/clusters/
  aligned_path: ./results/aligned/
  autoencoder_weights_path: ./results/models/autoencoder_weights
  output_path: ./results/454_output
  #  weights_path: ./results/models/454_weights
  weights_path: ./results/models/454_weights_snps
  ref_path: ./data/reference/REF
  aligned_ref_path: ./data/reference/aligned_REF
  unaligned_ref_path: ./data/reference/unaligned_454_REF
  number_of_batches: 100000
  batch_size: 500
  #  haplotype_length: 5000
  #  haplotype_length: 4860
  haplotype_length: 9721
  #  haplotype_length: 2432
  #  centroids_name: centroids
  haplotype_start: 789
  haplotype_end: 1186
  centroids_name: centroids_snp
  pooling: False
  SNP_pos: ./data/454_SNP_pos
  n_clusters: 5
  snp_positions: ./data/reference/snp_positions.txt

illumina:
  reads_path: ./data/Illumina
  mapped_reads_path: ./data/illumina_mapped
  #  one_hot_path: ./data/illumina_encoded_reads
  one_hot_path: ./data/illumina_encoded_snps
  #  weights_path: ./results/models/illumina_weights
  weights_path: ./results/models/illumina_weights_snps
  output_path: ./results/illumina_output
  ref_path: ./data/reference/REF
  aligned_ref_path: ./data/reference/aligned_REF
  unaligned_ref_path: ./data/reference/unaligned_illumina_REF
  haplotype_length: 9721
  number_of_batches: 9721
  #  centroids_name: illumina_centroids
  centroids_name: illumina_centroids_snps
  batch_size: 500
  n_clusters: 5
  pooling: False
  snp_positions: ./data/reference/snp_positions.txt

created:
  reads_path: ./data/created/reads
  mapped_reads_path: ./data/created/mapped
  one_hot_path: ./data/created/encoded_reads
  weights_path: ./results/models/created_weights_dataset
  output_path: ./results/created_output_dataset
  #  ref_path: ./data/reference/created_REF
  ref_path: ./data/created/reference/REF
  aligned_ref_path: ./data/created/reference/aligned_REF
  og_path: ./data/created/reference/0g_REF.fasta
  longest_path: ./data/created/reference/longest_REF
  snp_positions: ./data/created/reference/snp_positions
  haplotype_length: 350
  #  haplotype_length: 500
  number_of_batches: 250
  batch_size: 100
  centroids_name: centroids_created
  #  coverage: 100
  coverage: 50
  error: todo
  pooling: False
  read_length: 250
  number_of_strains: 5
  n_clusters: 3


per_gene:
  reads_path: ./data/Illumina
  mapped_reads_path: ./data/illumina_mapped

  ref_path: ./data/reference/REF
  aligned_ref_path: ./data/reference/aligned_REF
  unaligned_ref_path: ./data/reference/unaligned_illumina_REF
  haplotype_length: 9721
  number_of_batches: 9721
  #  centroids_name: illumina_centroids
  centroids_name: illumina_centroids_snps
  batch_size: 500
  n_clusters: 5
  pooling: False
  snp_positions: ./data/reference/snp_positions.txt

  #  p17
  one_hot_path: ./data/genes/illumina_encoded_snps_p17
  weights_path: ./results/models/illumina_weights_P17
  output_path: ./results/illumina_output_P17
  start: 789
  end: 1186

#  p24
#  one_hot_path: ./data/genes/illumina_encoded_snps_p24
#  weights_path: ./results/models/illumina_weights_p24
#  output_path: ./results/illumina_output_p24
#  start: 1185
#  end: 1879

#  p2p6
#  one_hot_path: ./data/genes/illumina_encoded_snps_p2p6
#  weights_path: ./results/models/illumina_weights_p2p6
#  output_path: ./results/illumina_output_p2p6
#  start: 1878
#  end: 2292

#  PR
#  one_hot_path: ./data/genes/illumina_encoded_snps_PR
#  weights_path: ./results/models/illumina_weights_PR
#  output_path: ./results/illumina_output_PR
#  start: 2252
#  end: 2550

#  RT
#  one_hot_path: ./data/genes/illumina_encoded_snps_RT
#  weights_path: ./results/models/illumina_weights_RT
#  output_path: ./results/illumina_output_RT
#  start: 2549
#  end: 3870

#  RNase
#  one_hot_path: ./data/genes/illumina_encoded_snps_RNase
#  weights_path: ./results/models/illumina_weights_RNase
#  output_path: ./results/illumina_output_RNase
#  start: 3869
#  end: 4230

#  int
#  one_hot_path: ./data/genes/illumina_encoded_snps_int
#  weights_path: ./results/models/illumina_weights_int
#  output_path: ./results/illumina_output_int
#  start: 4229
#  end: 5096

#  vif
#  one_hot_path: ./data/genes/illumina_encoded_snps_vif
#  weights_path: ./results/models/illumina_weights_vif
#  output_path: ./results/illumina_output_vif
#  start: 5040
#  end: 5620

#  vpr
#  one_hot_path: ./data/genes/illumina_encoded_snps_vpr
#  weights_path: ./results/models/illumina_weights_vpr
#  output_path: ./results/illumina_output_vpr
#  start: 5558
#  end: 5850

#  vpu
#  one_hot_path: ./data/genes/illumina_encoded_snps_vpu
#  weights_path: ./results/models/illumina_weights_vpu
#  output_path: ./results/illumina_output_vpu
#  start: 6061
#  end: 6310

#  gp120
#  one_hot_path: ./data/genes/illumina_encoded_snps_gp120
#  weights_path: ./results/models/illumina_weights_gp120
#  output_path: ./results/illumina_output_vif
#  start: 6224
#  end: 7758

#  gp41
#  one_hot_path: ./data/genes/illumina_encoded_snps_gp41
#  weights_path: ./results/models/illumina_weights_gp41
#  output_path: ./results/illumina_output_gp41
#  start: 7757
#  end: 8795

#  nef
#  one_hot_path: ./data/genes/illumina_encoded_snps_nef
#  weights_path: ./results/models/illumina_weights_nef
#  output_path: ./results/illumina_output_nef
#  start: 8796
#  end: 9417










