# choose data
data: experimental #created or experimental
pooling: False # running the network with or qithout pooling
verbose: 1 # set to 1 if you want tensorflow and Kmeans to give feedback on their progress and 0 otherwise
save: True  # saving weights and data as files
load: True  # saving weights and data from files if exists

created:
  # Change the following parameters
  haplotype_length: 1000
  batch_size: 500
  read_length: 250
  sequencing_error: 0.00473 #illumina; 0.0043 # 454/Roche
  threshold: 0
  n_clusters: 3
  coverage: 10

  # the following file are created automatically
  reads_path: ./data/created/reads
  mapped_reads_path: ./data/created/mapped
  one_hot_path: ./data/created/encoded_reads
  weights_path: ./results/models/created_weights_dataset
  output_path: ./results/created_output_dataset
  ref_path: ./data/created/reference/REF
  aligned_ref_path: ./data/created/reference/aligned_REF
  og_path: ./data/created/reference/0g_REF.fasta
  longest_path: ./data/created/reference/longest_REF
  snp_positions: ./data/created/reference/snp_positions


experimental:
  cleaned: True # if True, takes provided data, if False takes data from reads below
  source: Illumina #454/Roche
  reads_path: ./data/illumina # set path of the reads file
  hxb2_path: ./data/reference/hxb2.fasta # set path to hxb2 reference file
  ref_path: ./data/reference/REF # set path to reference file
  aligned_ref_path: ./data/reference/aligned_REF # set path to alilgned reference file
  mapped_reads_path: ./data/illumina_mapped
  global_snp_positions: ./data/reference/snp_positions
  haplotype_length: 9721
  n_clusters: 5
  batch_size: 500



  # uncomment the gene you wane run the program on

  #  p17
  name: p17
  reads: ./data/experimental/reads/p17.txt
  one_hot_path: ./data/experimental/encoded_snps_p17
  weights_path: ./results/models/weights_p17
  output_path: ./results/output_p17
  snp_positions: ./data/experimental/reference/snp_positions_p17.txt
  start: 789
  end: 1186
  start_ref: 0
  end_ref: 47

  #  p24
  #  name: p24
  #  reads: ./data/experimental/reads/p24.txt
  #  one_hot_path: ./data/experimental/encoded_snps_p24
  #  weights_path: ./results/models/weights_p24
  #  output_path: ./results/output_p24
  #  snp_positions: ./data/experimental/reference/snp_positions_p24.txt
  #  start: 1185
  #  end: 1879
  #  start_ref: 47
  #  end_ref: 92

  #  p2p6
  #  name: p2p6
  #  reads: ./data/experimental/reads/p2p6.txt
  #  one_hot_path: ./data/experimental/encoded_snps_p2p6
  #  weights_path: ./results/models/weights_p2p6
  #  output_path: ./results/output_p2p6
  #  snp_positions: ./data/experimental/reference/snp_positions_p2p6.txt
  #  start: 1878
  #  end: 2292
  #  start_ref: 92
  #  end_ref: 123
  #      end_ref: 132

  #  PR
  #  name: PR
  #  reads: ./data/experimental/reads/PR.txt
  #  one_hot_path: ./data//experimental/encoded_snps_PR
  #  weights_path: ./results/models/weights_PR
  #  output_path: ./results/output_PR
  #  snp_positions: ./data/experimental/reference/snp_positions_PR.txt
  #  start: 2252
  #  end: 2550
  #  start_ref: 122
  #  end_ref: 140

  #  RT
  #  name: RT
  #  reads: ./data/experimental/reads/RT.txt
  #  one_hot_path: ./data/experimental/encoded_snps_RT
  #  weights_path: ./results/models/weights_RT
  #  output_path: ./results/output_RT
  #  snp_positions: ./data/experimental/reference/snp_positions_RT.txt
  #  start: 2549
  #  end: 3870
  #  start_ref: 140
  #  end_ref: 227

  #  RNase
  #  name: RNase
  #  reads: ./data/experimental/reads/RNase.txt
  #  one_hot_path: ./data/experimental/encoded_snps_RNase
  #  weights_path: ./results/models/weights_RNase
  #  output_path: ./results/output_RNase
  #  snp_positions: ./data/experimental/reference/snp_positions_RNase.txt
  #  start: 3869
  #  end: 4230
  #  start_ref: 227
  #  end_ref: 264

  #  int
  #  name: int
  #  reads: ./data/experimental/reads/int.txt
  #  one_hot_path: ./data/experimental/encoded_snps_int
  #  weights_path: ./results/models/weights_int
  #  output_path: ./results/output_int
  #  snp_positions: ./data/experimental/reference/snp_positions_int.txt
  #  start: 4229
  #  end: 5096
  #  start_ref: 264
  #  end_ref: 310

  #  vif
  #  name: vif
  #  reads: ./data/experimental/reads/vif.txt
  #  one_hot_path: ./data/experimental/encoded_snps_vif
  #  weights_path: ./results/models/weights_vif
  #  output_path: ./results/output_vif
  #  snp_positions: ./data/experimental/reference/snp_positions_vif.txt
  #  start: 5040
  #  end: 5620
  #  start_ref: 308
  #  end_ref: 370

  #  vpr
  #  name: vpr
  #  reads: ./data/experimental/reads/vpr.txt
  #  one_hot_path: ./data/experimental/encoded_snps_vpr
  #  weights_path: ./results/models/weights_vpr
  #  output_path: ./results/output_vpr
  #  snp_positions: ./data/experimental/reference/snp_positions_vpr.txt
  #  start: 5558
  #  end: 5850
  #  start_ref: 367
  #  end_ref: 399

  #  vpu
  #  name: vpu
  #  reads: ./data/experimental/reads/vpu.txt
  #  one_hot_path: ./data/experimental/encoded_snps_vpu
  #  weights_path: ./results/models/weights_vpu
  #  output_path: ./results/output_vpu
  #  snp_positions: ./data/experimental/reference/snp_positions_vpu.txt
  #  start: 6061
  #  end: 6310
  #  start_ref: 399
  #  end_ref: 434

  #  gp120
  #  name: gp120
  #  reads: ./data/experimental/reads/gp120.txt
  #  one_hot_path: ./data/experimental/encoded_snps_gp120
  #  weights_path: ./results/models/weights_gp120
  #  output_path: ./results/output_vif
  #  snp_positions: ./data/experimental/reference/snp_positions_vif.txt
  #  start: 6224
  #  end: 7758
  #  start_ref: 423
  #  end_ref: 638

  #  gp41
  #  name: gp41
  #  reads: ./data/experimental/reads/gp41.txt
  #  one_hot_path: ./data/experimental/encoded_snps_gp41
  #  weights_path: ./results/models/weights_gp41
  #  output_path: ./results/output_gp41
  #  snp_positions: ./data/experimental/reference/snp_positions_gp41.txt
  #  start: 7757
  #  end: 8795
  #  start_ref: 638
  #  end_ref: 770

  #  nef
#  name: nef
#  reads: ./data/experimental/reads/nef.txt
#  one_hot_path: ./data/experimental/encoded_snps_nef
#  weights_path: ./results/models/weights_nef
#  output_path: ./results/output_nef
#  snp_positions: ./data/experimental/reference/snp_positions_nef.txt
#  start: 8796
#  end: 9417
#  start_ref: 770
#  end_ref: 859