# TODO create clear structure
# CAD
reads_file_path: "../Data/454/454.fasta"
haplotype_file_path: "../Data/reference/REF_fake.fasta"
#haplotype_file_path: "../Data/reference/REF.fasta"
name: "HIV_CAD"
save: True
load: True
real_data: False
max_read_length: 1006
max_created_read_length: 90

# create Data
number_of_strains: 2 # [1...5]
read_length: 10
min_number_of_reads_per_strain: 100000